merge -r651:671 $SVN_M/branches/stable

diff --git a/trunk/tools/svn2build b/trunk/tools/svn2build
--- a/trunk/tools/svn2build
+++ b/trunk/tools/svn2build
@@ -84,7 +84,13 @@ EOF
 			m4 $TMP/mondorescue.mc $dest/distributions/$dfam/$p.ebuild > $dest/distributions/${ddir}-$dver/$p-$v-r$TAG.ebuild
 		elif [ "$dtype" = "deb" ]; then
 			# To be developped
-			m4 $TMP/mondorescue.mc $dest/distributions/$dfam/$p > /dev/null
+			#m4 $TMP/mondorescue.mc $dest/distributions/$dfam/$p > /dev/null
+			cp -a $dest/distributions/$ddir/* $dest/distributions/${ddir}-$dver
+			$TOOLHOME/mkchangelog.pl $dtype $p $dest/distributions/${ddir}-$dver/changelog
+			if [ $? -ne 0 ]; then
+				echo "Unable to create changelog for ${ddir}-$dver/changelog"
+				exit -1
+			fi
 		else
 			echo "Unknown Build"
 		fi
@@ -133,7 +139,7 @@ EOF
 	#tar cfhj ${DEST}/$p-$v-$TAG.tar.bz2 $dest
 done
 
-rm -f $TMP/mondorescue.mc
+rm -rf $TMP
 
 echo "Version delivered :"
 echo "-------------------"
