svn merge -r288:291 $SVN_M/branches/2.06

diff --git a/trunk/mindi/mindi b/trunk/mindi/mindi
--- a/trunk/mindi/mindi
+++ b/trunk/mindi/mindi
@@ -1540,7 +1540,7 @@ OfferToCopyImagesToDisks() {
 	[ ! -e "$boot_dev" ] && Die "Cannot find $boot_dev - is your Linux distro broken?"
 	[ ! -e "$data_dev" ] && Die "Cannot find $data_dev - is your Linux distro broken?"
 	i=`find $imagesdir -type f | fgrep "/mindi-root.1" 2> /dev/null`
-	j=`find $imagesdir -type f | fgrep "/mindi-boot" | fgrep -v 2880`
+	j=`find $imagesdir -type f | fgrep "/mindi-boot" | egrep -v '2880|5760'`
 #    echo "i=$i"
 #    echo "j=$j"
 	if [ "$i" ] ; then
@@ -1754,16 +1754,16 @@ MakeLiloConfFile() {
 	disksize=$1
 	options=""
 		if [ "$ARCH" != "ia64" ] ; then
-		echo -en "boot=/dev/loop0\ndisk=/dev/loop0\n"
+			echo -en "boot=/dev/loop0\ndisk=/dev/loop0\n"
 		fi
 		if [ "$disksize" -eq "2880" ] ; then
-		echo -en "bios=0x00\nsectors=36\nheads=2\ncylinders=80\n"
+			echo -en "bios=0x00\nsectors=36\nheads=2\ncylinders=80\n"
 		elif [ "$disksize" -eq "1722" ] ; then
-		echo -en "bios=0x00\nsectors=21\nheads=2\ncylinders=82\n"
+			echo -en "bios=0x00\nsectors=21\nheads=2\ncylinders=82\n"
 		elif [ "$disksize" -gt "2880" ] ; then
 		    /bin/true
 		else
-		echo -en "bios=0x00\nsectors=18\nheads=2\ncylinders=80\n"
+			echo -en "bios=0x00\nsectors=18\nheads=2\ncylinders=80\n"
 		fi
 		if [ "$ARCH" != "ia64" ] ; then
 		    echo -en "install=/boot.b\nmap=/boot.map\n"
@@ -1771,15 +1771,16 @@ MakeLiloConfFile() {
 	if [ "$CDRECOVERY" = "yes" ] ; then
 		echo -en "default=RESTORE\n"
 	elif [ "$disksize" -gt "2880" ] && [ "`DidMondoCallMe`" ] ; then
-	if [ -e "$MONDO_TMP/start-nfs" ] ; then
-		echo -en "default=iso\n"
+		if [ -e "$MONDO_TMP/start-nfs" ] ; then
+			echo -en "default=iso\n"
+		else
+			echo -en "default=interactive\n"
+		fi
 	else
-		echo -en "default=interactive\n"
+		echo -en "default=expert\n"
 	fi
-	else
-	echo -en "default=expert\n"
-	fi
-		echo -en "prompt\n"
+
+	echo -en "prompt\n"
 	if [ "$ARCH" != "ia64" ] ; then
 		echo -en "vga=normal\nbackup=/dev/null\nmessage=/message\n"
 	fi
@@ -1801,12 +1802,12 @@ MakeLiloConfFile() {
 		    options="expert"
 	fi
 	else
-	options="expert"
+		options="expert"
 	fi
 	for i in $options ; do
 	ooo=$i
 	[ "$ooo" = "RESTORE" ] && ooo="nuke"
-		if [ "$ARCH" = "ia64" ] ; then
+	if [ "$ARCH" = "ia64" ] ; then
 		rootpart="root=/dev/ram0\n\t"
 	else
 		rootpart=""
@@ -2016,18 +2017,18 @@ PrepareBootDiskImage_SYSLINUX() {
 #    tar -zxf $MINDI_LIB/dev.tgz || LogIt "Cannot untar dev.tgz\n" <--- present for LILO; is it nec. for SYSLINUX too?
 	cat $sys_cfg_file | HackSyslinuxFile $ramdisk_size $mountpoint > syslinux.cfg || Die "Cannot copy syslinux.cfg from mindi_home to tmp_root"
 	if [ -e "$MONDO_TMP/start-nfs" ] ; then
-	mv syslinux.cfg syslinux.cfg.orig
-	sed s/interactive/iso/ syslinux.cfg.orig > syslinux.cfg
+		mv syslinux.cfg syslinux.cfg.orig
+		sed s/interactive/iso/ syslinux.cfg.orig > syslinux.cfg
 	fi
 	cd $old_pwd
 	echo "Copying $TMP_ROOT/mindi.rdz to $mountpoint/initrd.img..." >> $LOGFILE
 	cp -f $TMP_ROOT/mindi.rdz $mountpoint/initrd.img 2>> $LOGFILE
 	if [ "$?" -ne "0" ] ; then
-	LogIt "Failed to copy $TMP_ROOT/mindi.rdz to $mountpoint\n"
-	cat $TMP_ROOT/mtpt.$$ >> $LOGFILE
-	LogIt "Please unload some of your modules and try again.\n"
-	rm -f $TMP_ROOT/mtpt.$$
-	LogIt "Cannot incorporate mindi.rdz in bootdisk (kernel / modules too big?)\n"
+		LogIt "Failed to copy $TMP_ROOT/mindi.rdz to $mountpoint\n"
+		cat $TMP_ROOT/mtpt.$$ >> $LOGFILE
+		LogIt "Please unload some of your modules and try again.\n"
+		rm -f $TMP_ROOT/mtpt.$$
+		LogIt "Cannot incorporate mindi.rdz in bootdisk (kernel / modules too big?)\n"
 		retval=$(($retval+1))
 	fi
 
@@ -2040,13 +2041,13 @@ PrepareBootDiskImage_SYSLINUX() {
 	free_space=`df -k $mountpoint | tail -n1 | tr -s ' ' '\t' | cut -f4`
 	cp -f $kernelpath $mountpoint/vmlinuz &> /dev/null
 	if [ "$?" -ne "0" ] || [ "$FORCE_DUAL_FLOPPIES" = "yes" ] ; then
-	echo "Files at mountpoint ($mountpoint) :-" >> $LOGFILE
-	du -sk $mountpoint/* >> $LOGFILE
-	echo "--- end of list of files ---" >> $LOGFILE
-	echo -en "Kernel size = `du -sk $kernelpath | cut -f1` K\nRamdisk free = $free_space K\n\
+		echo "Files at mountpoint ($mountpoint) :-" >> $LOGFILE
+		du -sk $mountpoint/* >> $LOGFILE
+		echo "--- end of list of files ---" >> $LOGFILE
+		echo -en "Kernel size = `du -sk $kernelpath | cut -f1` K\nRamdisk free = $free_space K\n\
 Sorry, your kernel is too big for a boot/root floppy.\nI'll try the new boot/root two-disk thingy.\n" >> $LOGFILE
 		rm -f $mountpoint/vmlinuz
-	cd $old_pwd
+		cd $old_pwd
 		umount $mountpoint || Die "Cannot unmount mountpoint ($mountpoint)"
 		rmdir $mountpoint || LogIt "Cannot rmdir (PBDI)\n"
 #	losetup /dev/loop0 -d
@@ -2747,9 +2748,9 @@ TurnTgzIntoRdz() {
 	fi
 	floppy_modules=""
 	if [ "$disksize" -lt "2880" ] ; then
-	list_of_groovy_mods="$FLOPPY_MODS `WhichOfTheseModulesAreLoaded "$SCSI_MODS"`"
+		list_of_groovy_mods="$FLOPPY_MODS `WhichOfTheseModulesAreLoaded "$SCSI_MODS"`"
 	else
-	list_of_groovy_mods="$CDROM_MODS `WhichOfTheseModulesAreLoaded "$SCSI_MODS"`"
+		list_of_groovy_mods="$CDROM_MODS `WhichOfTheseModulesAreLoaded "$SCSI_MODS"`"
 	fi
 	if [ -e "$MONDO_TMP/start-nfs" ] ; then
 		cp -a $MONDO_TMP/start-nfs $mountpoint/sbin
@@ -3191,15 +3192,15 @@ if [ "$USE_LILO" = "yes" ] ; then
 	fi
 else
 	if ! PrepareBootDiskImage_SYSLINUX $imagesdir 1722 $kernelpath $ramdisk_size ; then
-	LogIt "Warning - failed to create 1.72MB boot image. Please reduce your kernel's size\n"
-	LogIt "if you want to make a 1.72MB floppy disk.\n"
+		LogIt "Warning - failed to create 1.72MB boot image. Please reduce your kernel's size\n"
+		LogIt "if you want to make a 1.72MB floppy disk.\n"
+		if ! PrepareBootDiskImage_SYSLINUX $imagesdir 2880 $kernelpath $ramdisk_size ; then
+			LogIt "Warning - failed to create 2.88MB floppy disk image.\n"
+			LogIt "Please reduce your kernel's size\n"
+			LogIt "if you want to make a 2.88MB floppy disk.\n"
+			PrepareBootDiskImage_SYSLINUX $imagesdir 5760 $kernelpath $ramdisk_size || Die "Failed to create 5.76MB floppy disk image."
+		fi
 	fi
-	if ! PrepareBootDiskImage_SYSLINUX $imagesdir 2880 $kernelpath $ramdisk_size ; then
-		LogIt "Warning - failed to create 2.88MB floppy disk image.\n"
-		LogIt "Please reduce your kernel's size\n"
-		LogIt "if you want to make a 2.88MB floppy disk.\n"
-	fi
-	PrepareBootDiskImage_SYSLINUX $imagesdir 5760 $kernelpath $ramdisk_size || Die "Failed to create 5.76MB floppy disk image."
 fi
 
 
