merge -r 542:560 $SVN_M/branches/stable

diff --git a/trunk/mindi/mindi b/trunk/mindi/mindi
--- a/trunk/mindi/mindi
+++ b/trunk/mindi/mindi
@@ -1366,7 +1366,7 @@ absolute_partition old_partition_fmt
 	
 	if [ -d "/proc/lvm" ] || [ -d "/dev/mapper" ]; then
 	echo -en "\rAnalyzing LVM...\r"
-	all_partitions=`$MINDI_SBIN/analyze-my-lvm | fgrep ">>>" | cut -d' ' -f2-32`
+	all_partitions=`$MINDI_LIB/analyze-my-lvm | fgrep ">>>" | cut -d' ' -f2-32`
 	fi
 	all_partitions="$all_partitions `ListAllPartitions 2> /dev/null`"
 #    echo "all partitions = $all_partitions" > /dev/stderr
@@ -2144,6 +2144,132 @@ Sorry, your kernel is too big for a boot/root floppy.\nI'll try the new boot/roo
 	fi
 	[ "$retval" -ne "0" ] && LogIt "PrepareBootDiskImage() is returning nonzero\n"
 	return $retval
+}
+
+
+PrepareDataDiskImages() {
+	local needlist bigdir minidir_root tardir diskdir imagesdir res i j k old_pwd lines
+
+	imagesdir=$1
+	rm -f $imagesdir/mindi-*.img $imagesdir/[0-9]*.tar.gz $imagesdir/mindi.iso
+	needlist=$TMP_ROOT/what-we-need.txt
+	bigdir=$TMP_ROOT/bigdir
+	minidir_root=$TMP_ROOT/minidir
+	mkdir -p $minidir_root
+	mkdir -p $bigdir/usr/bin
+	tardir=$TMP_ROOT/tardir
+
+	lines=`grep -vx " *#.*" $MINDI_CONF/deplist.txt | grep -vx "" | wc -l`
+	cat $MINDI_CONF/deplist.txt | GenerateGiantDependencyList $needlist $lines
+	res=$?
+	if [ "$YOUR_KERNEL_SUCKS" ]; then
+	pwd=`pwd`
+	cd $TMP_ROOT
+		for i in `ListKernelModulePaths | HackPathsToFailsafe` ; do
+		cp --parents -pRdf ./$i $bigdir || Die "PDDI can't cp $i->$bigdir"
+		if [ "`du -sk $i | cut -f1`" -lt "$(($CHOPSIZE*2))" ] ; then
+		cp --parents -pRdf $i $bigdir
+		else
+		ChopUpAndCopyFile $i $bigdir $CHOPSIZE $BIGNO
+		BIGNO=$(($BIGNO+1))
+		fi
+	done
+	for i in $EXTRA_MODS ; do
+		j=`find lib/modules/$FAILSAFE_KVER -name $i.*o 2> /dev/null`
+		[ ! "$j" ] && echo "Warning - cannot find failsafe module $i.o" >> $LOGFILE
+		for k in $j ; do
+		if [ "`du -sk $k | cut -f1`" -lt "$CHOPSIZE" ] ; then
+		    cp --parents -pRdf $k $bigdir
+		else
+		    ChopUpAndCopyFile $k $bigdir $CHOPSIZE $BIGNO
+		    BIGNO=$(($BIGNO+1))
+		fi
+		echo "Added failsafe module $k to ramdisk" >> $LOGFILE
+		done
+	done
+	cd $pwd
+	else
+	ListKernelModulePaths >> $needlist
+	fi
+	if [ "$res" -ne "0" ] ; then
+		Die "You have $res file`PluralOrNot $res` present in dependency list\nbut absent from filesystem."
+	fi
+	FindAndAddUserKeyboardMappingFile
+	mkdir -p $bigdir/tmp
+	if [ "`DidMondoCallMe`" ] ; then
+		MakeMondoConfigFile $TMP_ROOT/mondo-restore.cfg
+		cp -f $TMP_ROOT/mondo-restore.cfg $bigdir/tmp &> /dev/null
+		cp -f $TMP_ROOT/mondo-restore.cfg $CACHE_LOC &> /dev/null
+	fi
+	[ -d "/mnt/.boot.d" ] && echo "Oh Jebus" > $bigdir/tmp/DUMBASS-GENTOO
+	DropOptimizedLibraries $needlist $bigdir
+	echo -en "Assembling dependency files"
+	CopyDependenciesToDirectory < $needlist $bigdir
+
+# also copy io.sys and msdos.sys, if we can find them
+	for i in `mount | cut -d' ' -f3` ; do
+	for j in io.sys msdos.sys ; do
+		[ -e "$i/$j" ] && cp -f $i/$j $bigdir
+	done
+	done
+
+# master boot record, too
+	i=`cat $MONDO_TMP/BOOTLOADER.DEVICE 2> /dev/null`
+	if [ "$i" ] ; then
+	LogIt "Backing up $i's MBR\n"
+	dd if=$i of=$bigdir/BOOTLOADER.MBR bs=446 count=1 >> $LOGFILE 2>> $LOGFILE
+# < < E O F
+	sleep 1
+	sync
+#        [ "$?" -ne "0" ] && echo "Failed to save $i's MBR to bigdir" >> $LOGFILE
+	j=$i
+	[ -h "$j" ] && j=`ResolveSoftlink $j`
+	LogIt "Creating /dev/boot_device ($j)\n"
+	mkdir -p $bigdir/dev
+	cp -pRdf $j $bigdir/dev/boot_device || Die "Unable to create /dev/boot_device on ramdisk"
+	fi
+
+# more stuff
+#    cp -f $MINDI_LIB/embleer* $bigdir
+	old_pwd=`pwd`
+	cd $bigdir
+
+	[ -e "$MINDI_LIB/aux-tools" ] || Die "aux-tools not found in Mindi's home dir. Do you have multiple copies of Mindi lying around? Please delete them. No, don't e-mail me and ask how. ;) Use 'rm'."
+	cp -Rdf $MINDI_LIB/aux-tools/* . 2>> $LOGFILE || LogIt "Warning - error occurred while unzipping aux-tools\n"
+	if [ -e "$MINDI_LIB/x11-tools.tgz" ] ; then
+	tar -zxf $MINDI_LIB/x11-tools.tgz 2>> $LOGFILE || LogIt "Warning - error occurred while unzipping x11-tools.tgz\n"
+	fi
+	if [ -e "$MONDO_SHARE/restore-scripts" ] ; then
+		cp -Rdf $MONDO_SHARE/restore-scripts/* . 2>> $LOGFILE
+		[ "$?" -ne "0" ] && [ "`DidMondoCallMe`" ] && Die "Cannot find/install $MONDO_SHARE/restore-scripts"
+	fi
+	[ -d "/lib/dev-state" ] && cp --parents -pRdf /lib/dev-state .
+	cd $old_pwd
+	echo -e "$DONE"
+	TOTAL_BIGDIR_SIZE=`du -sk $bigdir | cut -f1`
+	SplitDirectoryIntoMinidirs $bigdir $minidir_root
+	noof_disks=$?
+	[ "$noof_disks" -eq "0" ] && Die "Too much stuff!"
+#    if [ "$noof_disks" -ge "8" ] ; then
+#        LogIt "You are putting a ludicrously large amount of data on these disks."
+#        LogIt "I shall therefore double EXTRA_SPACE, just in case your ramdisk is too small."
+#        EXTRA_SPACE=$(($EXTRA_SPACE*2))
+#    fi
+	MakeMountlist $TMP_ROOT/mountlist.txt
+	mkdir -p $minidir_root/$noof_disks/tmp
+	cp -f $TMP_ROOT/mountlist.txt $minidir_root/$noof_disks/tmp/mountlist.txt || Die "Cannot copy mountlist.txt from $TMP_ROOT to data disk"
+	cp -f $TMP_ROOT/mountlist.txt $CACHE_LOC
+	[ "`DidMondoCallMe`" ] && cp -f $minidir_root/$noof_disks/tmp/mountlist.txt $MONDO_TMP/.
+	[ -d "/proc/lvm" ] && $MINDI_LIB/analyze-my-lvm > $minidir_root/$noof_disks/tmp/i-want-my-lvm
+	[ -d "/dev/mapper" ] && $MINDI_LIB/analyze-my-lvm > $minidir_root/$noof_disks/tmp/i-want-my-lvm
+	cat $minidir_root/$noof_disks/tmp/mountlist.txt >> $LOGFILE
+	ZipMinidirsIntoTarballs $minidir_root $tardir $noof_disks
+	CreateDataDiskImagesFromTarballs $tardir $imagesdir $noof_disks
+	FRIENDLY_OUTSTRING="Boot and data disk images were created."
+# One 1.72MB boot disk, one 2.88MB boot disk and $noof_disks data disk images
+	rmdir $tardir $bigdir
+	rm -f $needlist
+	return $noof_disks
 }
 
 
