Allow 5670 MB fllopy disks for lilo as well

diff --git a/branches/stable/mindi/mindi b/branches/stable/mindi/mindi
--- a/branches/stable/mindi/mindi
+++ b/branches/stable/mindi/mindi
@@ -3218,10 +3218,15 @@ if [ "$USE_LILO" = "yes" ] ; then
 		PrepareBootDiskImage_LILO $imagesdir $IA64_BOOT_SIZE $kernelpath $ramdisk_size || Die "Failed to create ia64 floppy disk image."
 	else
 		if ! PrepareBootDiskImage_LILO $imagesdir 1722 $kernelpath $ramdisk_size ; then
-		LogIt "Warning - failed to create 1.72MB boot image. Please reduce your kernel's size\n"
-		LogIt "if you want to make a 1.72MB floppy disk.\n"
+			LogIt "Warning - failed to create 1.72MB boot image. Please reduce your kernel's size\n"
+			LogIt "if you want to make a 1.72MB floppy disk.\n"
 		fi
-		PrepareBootDiskImage_LILO $imagesdir 2880 $kernelpath $ramdisk_size || Die "Failed to create 2.88MB floppy disk image."
+		if ! PrepareBootDiskImage_LILO $imagesdir 2880 $kernelpath $ramdisk_size ;  then
+			LogIt "Warning - failed to create 2.88MB floppy disk image.\n"
+			LogIt "Please reduce your kernel's size\n"
+			LogIt "if you want to make a 2.88MB floppy disk.\n"
+			PrepareBootDiskImage_LILO $imagesdir 5760 $kernelpath $ramdisk_size || Die "Failed to create 2.88MB floppy disk image."
+		fi
 	fi
 else
 	if ! PrepareBootDiskImage_SYSLINUX $imagesdir 1722 $kernelpath $ramdisk_size ; then
